### ISSUE TITLE
PHP Composer——自动加载原理命名空间分割符号你写错了

### ISSUE THREAD

**Issue by watermelon-brother** [LeoYang90/laravel-source-analysis#3]
我们以laravel中第三方库Symfony其中一个命名空间/Symfony/Core/Request为例，讲一讲上面PSR0标准。
应该改为这样
/Symfony/Core/Request  => \Symfony\Core\Request

差点被你坑死啊！哥们！

**Comment by LeoYang90** [comment]
已修改，谢谢！
